# Generated by Django 3.0.5 on 2020-04-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200428_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='e',
            new_name='e_to',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n',
            new_name='n_to',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='s',
            new_name='s_to',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='w',
            new_name='w_to',
        ),
    ]
